/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Isla.glb --types 
*/

import * as THREE from 'three'
type GLTFAction = THREE.AnimationClip;
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Cubo: THREE.Mesh
    Cubo001: THREE.Mesh
    Cubo002: THREE.Mesh
    Isla: THREE.Mesh
    Agua: THREE.Mesh
    Roca_1: THREE.Mesh
    Roca_2: THREE.Mesh
    Roca_3: THREE.Mesh
    Arbol: THREE.Mesh
    Arbol001: THREE.Mesh
  }
  materials: {
    colorr: THREE.MeshStandardMaterial
    color: THREE.MeshStandardMaterial
    arco: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Isla (props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/Isla.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cubo.geometry} material={materials.colorr} position={[-0.52, 1.298, -4.775]} scale={[0.956, 2.869, 0.956]} />
      <mesh geometry={nodes.Cubo001.geometry} material={materials.color} position={[-0.341, 1.757, 1.941]} scale={[0.956, 2.869, 0.956]} />
      <mesh geometry={nodes.Cubo002.geometry} material={materials.arco} position={[-1.655, 1.394, 8.454]} scale={[0.956, 2.869, 0.956]} />
      <mesh geometry={nodes.Isla.geometry} material={materials.Material} />
      <mesh geometry={nodes.Agua.geometry} material={materials.Material} position={[9.859, 0.283, -0.003]} />
      <mesh geometry={nodes.Roca_1.geometry} material={materials.Material} position={[9.132, 0.633, -1.666]} />
      <mesh geometry={nodes.Roca_2.geometry} material={materials.Material} position={[9.126, 0.616, 1.495]} rotation={[0.146, 0.109, -0.06]} scale={1.48} />
      <mesh geometry={nodes.Roca_3.geometry} material={materials.Material} position={[8.532, 0.552, -0.287]} rotation={[2.944, 0.744, -3.051]} scale={1.714} />
      <mesh geometry={nodes.Arbol.geometry} material={materials.Material} position={[-0.103, 2.743, 0.215]} rotation={[0.082, -0.188, 0.015]} scale={[0.778, 0.426, 0.778]} />
      <mesh geometry={nodes.Arbol001.geometry} material={materials['Material.002']} position={[-2.294, 2.354, 0]} rotation={[2.941, 1.156, -2.958]} scale={[0.612, 0.335, 0.612]} />
    </group>
  )
}

useGLTF.preload('/Isla.glb')
